### ISSUE TITLE
where should I place the toml file and the freenerf folder in the directory of NerfStudio

### ISSUE THREAD

**Issue by TaoInAnytime** [FDUEDREF3/FreeNeRF_NeRFStudio#1]
Hello, may I know where should I place the toml file and the freenerf folder in the directory of NerfStudio?

**Comment by TaoInAnytime** [comment]
> Hello, may I know where should I place the toml file and the freenerf folder in the directory of NerfStudio?

solved by refering to https://github.com/kerrj/lerf/tree/main

**Comment by Mabel0403** [comment]
Hello @TaoF02 , may I know which version of nerfstudio you are using？I tried a lot of versions of nerfstudio, but each version is not compatible with freenerf.
